

SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;
GO


PRINT N'Creating SqlTable [dbo].[Table_1]...';

GO
CREATE TABLE [dbo].[Table_1] (
    [col1] NCHAR (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
);


GO

PRINT N'Creation is complete.';

GO
