name: Downgrade Workflow

env:
  RUNNERS_OPTIONS: -c cookies=enabled
  jarPath: "C:\\Program Files (x86)\\DBmaestro\\DOP Server\\Agent\\DBmaestroAgent.jar"
  DBMprojectName: "BrdJiraGitHub"
  DBMauthType: "DBmaestroAccount"
  DBMuserName: "su@dbmaestro.com"
  DBMauthToken: "zhsiecDKHTGeZBodgykvX1O5H0E5YzaI"
  jira_secret: "c2VyZ2lvbEBkYm1hZXN0cm8uY29tOkFUQVRUM3hGZkdGMDg2emFINXBsdmJ1MXhTbC1YWXhFaHJxZFZSWHZ0Wk1ibGgzVDBSQ3RmX0lqVlQ2U0hzTENRcEtvWWpvTFk4UHBjZjZaMVBwZWMyZFlqU2diSERiRTVMVVVqMDBKRUhHazZDRlhscXhkUG9GQlpicHFQaEhCejRhNlZVX2Z2MVJERHp3NDZvR3RkaUw3SXZGeDR6ME9UeTNKOUhZYUNIdkNCamlKd2hBVVJkOD1DREY5Qjg5Mw=="
  DBMserver: "SER1:8017"
  LOCAL_PATH: "C:\\workspace\\jira-github-lab\\"
  NEW_STATE: ${{ github.event.client_payload.new_state_id}}

on:
  repository_dispatch:
    types: rollback
  workflow_dispatch:

jobs:
  rollback:
    runs-on: self-hosted

    steps:
      - name: Downgrading RS and QA Environment
        if: ${{ env.NEW_STATE == '10000' }} 
        run: |
              echo "Downgrading"
              $uri = "https://sergiodbm.atlassian.net/rest/api/2/issue/${{ github.event.client_payload.package_id }}"
              $headers = @{
                  "Authorization" = "Basic ${{ env.jira_secret }}"
                  "Content-Type" = "application/json"
              }
              java -jar "${{ env.jarPath }}" -Rollback -ProjectName "${{ env.DBMprojectName }}"  -EnvName "Release Source" -PackageName " ${{ github.event.client_payload.package_id }}" -BackupBehavior True -RestoreBehavior True -Server "${{ env.DBMserver }}" -UseSSL False -AuthType DBmaestroAccount -UserName "${{ env.DBMuserName }}" -Password "${{ env.DBMauthToken }}"
              java -jar "${{ env.jarPath }}" -Rollback -ProjectName "${{ env.DBMprojectName }}"  -EnvName "QA_Env_1" -PackageName " ${{ github.event.client_payload.package_id }}" -BackupBehavior True -RestoreBehavior True -Server "${{ env.DBMserver }}" -UseSSL False -AuthType DBmaestroAccount -UserName "${{ env.DBMuserName }}" -Password "${{ env.DBMauthToken }}"                  
              if ($LastExitCode -eq 0) {
                $issue_status = "RollbackRS_OK"
              } else {
                $issue_status = "RollbackRS_ERROR"
              }
              $body = @{ "fields" = @{"customfield_10238" = @($issue_status) } } | ConvertTo-Json
              Invoke-RestMethod -Uri $uri -Method Put -Headers $headers -Body $body
              - name: Downgrading RS and QA Environment
        
      - name: Downgrading Prod Environment
        if: ${{ env.NEW_STATE == '10002' }} 
        run: |
              echo "Downgrading"
              $uri = "https://sergiodbm.atlassian.net/rest/api/2/issue/${{ github.event.client_payload.package_id }}"
              $headers = @{
                  "Authorization" = "Basic ${{ env.jira_secret }}"
                  "Content-Type" = "application/json"
              }
              java -jar "${{ env.jarPath }}" -Rollback -ProjectName "${{ env.DBMprojectName }}"  -EnvName "Prod_Env_1" -PackageName " ${{ github.event.client_payload.package_id }}" -BackupBehavior True -RestoreBehavior True -Server "${{ env.DBMserver }}" -UseSSL False -AuthType DBmaestroAccount -UserName "${{ env.DBMuserName }}" -Password "${{ env.DBMauthToken }}"
              if ($LastExitCode -eq 0) {
                $issue_status = "RollbackProd_OK"
              } else {
                $issue_status = "RollbackProd_ERROR"
              }
              $body = @{ "fields" = @{"customfield_10238" = @($issue_status) } } | ConvertTo-Json
              Invoke-RestMethod -Uri $uri -Method Put -Headers $headers -Body $body



