name: Downgrade Workflow

env:
  RUNNERS_OPTIONS: -c cookies=enabled
  jarPath: "C:\\Program Files (x86)\\DBmaestro\\DOP Server\\Agent\\DBmaestroAgent.jar"
  DBMprojectName: "BrdJiraGitHub"
  DBMauthType: "DBmaestroAccount"
  DBMuserName: "su@dbmaestro.com"
  DBMauthToken: "zhsiecDKHTGeZBodgykvX1O5H0E5YzaI"
  jira_secret: "ATATT3xFfGF08wUBk8Adbx0zDBPqiB78ISQGv0K5VYlbq9hOLd5bc0iATB8-0S-Ni0enqZqRw2o4x_s3Y8m_Te9Y9alai7zPy_kttmRHbR9sBf8qGl1AphK6tDNfxyRkOY5A6vxDQ3BOwlQiJ5bRONQAQZHcDa9_T8A_y2TtHdUYLbr8qDxMfxE=B9BF0CB4"
  DBMserver: "SER1:8017"
  LOCAL_PATH: "C:\\workspace\\jira-github-lab\\"
  NEW_STATE: ${{ github.event.client_payload.new_state_id}}

on:
  repository_dispatch:
    types: rollback
  workflow_dispatch:

jobs:
  rollback:
    runs-on: self-hosted

    steps:
      - name: Print Event
        run: |
              echo "This is a triggered event. Condition is:  ${{ github.event.client_payload.dbm_action }} , Package name is: ${{ github.event.client_payload.package_id }} , Status id is: ${{ env.NEW_STATE }}" 
              echo "Jira new state id:   ${{ github.event.client_payload.new_state_id }}" 
        
      - name: Downgrading DBM Environment
        run: |
             echo "Downgrading"
                 if ( ${{ env.NEW_STATE }} -eq 10000 ) 
                  {
                    java -jar "${{ env.jarPath }}" -Rollback -ProjectName "${{ env.DBMprojectName }}"  -EnvName "Release Source" -PackageName " ${{ github.event.client_payload.package_id }}" -BackupBehavior True -RestoreBehavior True -Server "${{ env.DBMserver }}" -UseSSL False -AuthType DBmaestroAccount -UserName "${{ env.DBMuserName }}" -Password "${{ env.DBMauthToken }}"
                    java -jar "${{ env.jarPath }}" -Rollback -ProjectName "${{ env.DBMprojectName }}"  -EnvName "QA_Env_1" -PackageName " ${{ github.event.client_payload.package_id }}" -BackupBehavior True -RestoreBehavior True -Server "${{ env.DBMserver }}" -UseSSL False -AuthType DBmaestroAccount -UserName "${{ env.DBMuserName }}" -Password "${{ env.DBMauthToken }}"                  }
              elseif ( ${{ env.NEW_STATE }} -eq 10002 ) 
                  {
                    java -jar "${{ env.jarPath }}" -Upgrade -ProjectName "${{ env.DBMprojectName }}"  -EnvName "Prod_Env_1" -PackageName " ${{ github.event.client_payload.package_id }}" -BackupBehavior True -RestoreBehavior True -Server "${{ env.DBMserver }}" -UseSSL False -AuthType DBmaestroAccount -UserName "${{ env.DBMuserName }}" -Password "${{ env.DBMauthToken }}"
                  }
              else
                  {
                  echo ${{ github.event.client_payload.dbm_action }}
                  Write-Output "Downgrade Transition not found ${{ env.NEW_STATE }}"
                  }
   


