name: Precheck With Action Workflow

env:
  RUNNERS_OPTIONS: -c cookies=enabled
  jarPath: "C:\\Temp\\dbm-agent-jar\\DBmaestroAgent.jar"
  DBMprojectName: "BrdJiraGitHub"
  DBMauthType: "DBmaestroAccount"
  DBMuserName: "su@dbmaestro.com"
  DBMauthToken: "zhsiecDKHTGeZBodgykvX1O5H0E5YzaI"
  jira_secret: "ATATT3xFfGF08wUBk8Adbx0zDBPqiB78ISQGv0K5VYlbq9hOLd5bc0iATB8-0S-Ni0enqZqRw2o4x_s3Y8m_Te9Y9alai7zPy_kttmRHbR9sBf8qGl1AphK6tDNfxyRkOY5A6vxDQ3BOwlQiJ5bRONQAQZHcDa9_T8A_y2TtHdUYLbr8qDxMfxE=B9BF0CB4"
  DBMserver: "SER1:8017"
  local_path: "C:\\workspace\\jira-github-lab\\"
  new_state: ${{ github.event.client_payload.new_state_id}}

on:
  repository_dispatch:
    types: precheck_action
  workflow_dispatch:

jobs:
  precheck:
    if: ${{ github.event.client_payload.new_state_id == '10004' }}
    runs-on: self-hosted
    steps:

      - name: Get DBMaestroAgent.jar file
        run: |
            cd "C:\\Temp\\dbm-agent-jar"
            git fetch
            git checkout tags/v24.1.0.11442

      - name: Checkout files
        run: |
              echo "This is a triggered event. Condition is:  ${{ github.event.client_payload.dbm_action }} , Package name is: ${{ github.event.client_payload.package_name }} , Status id is: ${{ env.new_state }}" 
              cd ${{ env.local_path }}
              git pull origin


      - name: Package Creation 
        uses: sergioldbm/dbm-github-action@main
        with:
          command: 'CreateManifestFileAndPackage'
          package_name: ${{ github.event.client_payload.package_name }}
          files_path: "${{ env.local_path }}packages"
          project_id: ${{ env.DBMprojectName }}
          server: ${{ env.DBMserver }}
          env_name: 'Release Source'
          user_name: ${{ env.DBMuserName }}
          password: ${{ env.DBMauthToken }}
          jar_path: ${{ env.jarPath }}

      - name: Precheck Package
        run: |
              java -jar "${{ env.jarPath }}" -PreCheck -ProjectName "${{ env.DBMprojectName }}" -Server "${{ env.DBMserver }}" -PackageName "${{ github.event.client_payload.package_name }}" -UseSSL False -AuthType DBmaestroAccount -UserName "${{ env.DBMuserName }}" -Password "${{ env.DBMauthToken }}"



