name: Precheck Workflow

env:
  RUNNERS_OPTIONS: -c cookies=enabled
  DBMprojectName: "BrdJiraGitHub"
  DBMauthType: "DBmaestroAccount"
  DBMuserName: "su@dbmaestro.com"
  DBMauthToken: "zhsiecDKHTGeZBodgykvX1O5H0E5YzaI"
  jira_secret: "c2VyZ2lvbEBkYm1hZXN0cm8uY29tOkFUQVRUM3hGZkdGMDg2emFINXBsdmJ1MXhTbC1YWXhFaHJxZFZSWHZ0Wk1ibGgzVDBSQ3RmX0lqVlQ2U0hzTENRcEtvWWpvTFk4UHBjZjZaMVBwZWMyZFlqU2diSERiRTVMVVVqMDBKRUhHazZDRlhscXhkUG9GQlpicHFQaEhCejRhNlZVX2Z2MVJERHp3NDZvR3RkaUw3SXZGeDR6ME9UeTNKOUhZYUNIdkNCamlKd2hBVVJkOD1DREY5Qjg5Mw=="
  DBMserver: "SER1:8017"
  local_path: "C:\\workspace\\jira-github-lab\\"
  agent_jar_path: "C:\\Temp\\dbm-agent-jar\\DBmaestroAgent.jar"
  new_state: ${{ github.event.client_payload.new_state_id}}
  #workflowstates
  READY_TO_REVIEW_STATUS_ID: '10004'
  

on:
  repository_dispatch:
    types: precheck
  workflow_dispatch:

jobs:
  # Job executed for Package Prechek. Triggered when Jira state transitions to Ready To Review.
  # The Job creates the Package and runs DBM Precheck. 
  precheck:
    if: ${{ github.event.client_payload.new_state_id == vars.READY_TO_REVIEW_STATUS_ID }}
    runs-on: self-hosted
    steps:
      - name: Package Creation 
        # Creates the DBMaestro Package, generating the manifest, zip file, 
        # and uploading it to DBMaestro.
        uses: DBMaestroDev/dbm_github_actions/dbm-create-package@v1
        with:
          command: 'CreateManifestFileAndPackage'
          package_name: ${{ github.event.client_payload.package_name }}
          files_path: "${{ env.local_path }}packages"
          project_id: ${{ env.DBMprojectName }}
          server: ${{ env.DBMserver }}
          env_name: 'Release Source'
          user_name: ${{ env.DBMuserName }}
          password: ${{ env.DBMauthToken }}
          jar_path: "${{ env.agent_jar_path }}"

      - name: Precheck Package
        # Prechecks the package in DBMaestro, verifying Policy compliance. 
        # Updates the result of the Precheck, to Jira Issue
        run: |
              java -jar "${{ env.agent_jar_path }}" -PreCheck -ProjectName "${{ env.DBMprojectName }}" -Server "${{ env.DBMserver }}" -PackageName "${{ github.event.client_payload.package_name }}" -UseSSL False -AuthType DBmaestroAccount -UserName "${{ env.DBMuserName }}" -Password "${{ env.DBMauthToken }}"

             
  ServiceNowDevOpsChange:
    # jobs that must complete successfully before this job will run
    needs: precheck
    # type of machine to run the job on
    runs-on: self-hosted
    name: 'ServiceNow DevOps Change'
    steps:
      - name: ServiceNow Change
        uses: ServiceNow/servicenow-devops-change@v3.0.0
        with:
          # Devops Integration Token
          devops-integration-token: "yL2q9eTNL97fL7xsdajFZ3GxveZHXBAe"
          # ServiceNow Instance URL
          instance-url: "https://dev244514.service-now.com/"
          # Orchestration Tool Id
          tool-id: "3b63f7be53998210b1895eb0a0490efb"
          #tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          # GitHub Context
          context-github: ${{ toJSON(github) }}
          # Display Name of the Job
          job-name: 'ServiceNow DevOps Change'
          change-request: '{"attributes":{"requested_by":{"name": "Test User"},"assignment_group":{"name": "Change Approval Team"},"priority": "2","comments": "This is a sample pipeline script to be added in your change step","work_notes": "Update this to work_notes","start_date": "2023-09-07 11:59:59","end_date": "2023-09-09 11:59:59"}}'


